// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI4UFFcy_Y8nXczMptO2muCl8R8rLw4D4',
    appId: '1:732424620293:web:7d3ebb4b86b68a339ecf6c',
    messagingSenderId: '732424620293',
    projectId: 'instagram-52dee',
    authDomain: 'instagram-52dee.firebaseapp.com',
    storageBucket: 'instagram-52dee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGgBrVYTMm1cR2tjugqb6fHvNSY8Uym-Q',
    appId: '1:732424620293:android:e29f66d8c9833dcb9ecf6c',
    messagingSenderId: '732424620293',
    projectId: 'instagram-52dee',
    storageBucket: 'instagram-52dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3KXNVKN3r3UzQEpJ_N7RHVEMzhcLZtdk',
    appId: '1:732424620293:ios:2b3fb74f394816fc9ecf6c',
    messagingSenderId: '732424620293',
    projectId: 'instagram-52dee',
    storageBucket: 'instagram-52dee.appspot.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3KXNVKN3r3UzQEpJ_N7RHVEMzhcLZtdk',
    appId: '1:732424620293:ios:2b3fb74f394816fc9ecf6c',
    messagingSenderId: '732424620293',
    projectId: 'instagram-52dee',
    storageBucket: 'instagram-52dee.appspot.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI4UFFcy_Y8nXczMptO2muCl8R8rLw4D4',
    appId: '1:732424620293:web:2e9bce26e37658799ecf6c',
    messagingSenderId: '732424620293',
    projectId: 'instagram-52dee',
    authDomain: 'instagram-52dee.firebaseapp.com',
    storageBucket: 'instagram-52dee.appspot.com',
  );
}
